apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vedtaksfeed
  namespace: tbd
  labels:
    team: tbd
spec:
  port: 8080
  liveness:
    path: isalive
  readiness:
    path: isready
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: speed-api
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-vedtaksfeed-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
