[versions]
tbdLibs = "20261005.1432"
sykepengerGradlePlugins = "20261001.1830"

[libraries]
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }

awaitility = "org.awaitility:awaitility:4.3.0"
commons-codec = "commons-codec:commons-codec:1.22.1"
mockk = "io.mockk:mockk:1.14.11"
wiremock = "org.wiremock:wiremock-jetty12:3.13.2"

rapidsAndRivers = "com.github.navikt:rapids-and-rivers:2026091610031789545782"

tbdLibs-azureTokenClientDefault = { module = "com.github.navikt.tbd-libs:azure-token-client-default", version.ref = "tbdLibs" }
tbdLibs-kafkaTest = { module = "com.github.navikt.tbd-libs:kafka-test", version.ref = "tbdLibs" }
tbdLibs-naisfulApp = { module = "com.github.navikt.tbd-libs:naisful-app", version.ref = "tbdLibs" }
tbdLibs-naisfulTestApp = { module = "com.github.navikt.tbd-libs:naisful-test-app", version.ref = "tbdLibs" }
tbdLibs-rapidsAndRiversTest = { module = "com.github.navikt.tbd-libs:rapids-and-rivers-test", version.ref = "tbdLibs" }
tbdLibs-retry = { module = "com.github.navikt.tbd-libs:retry", version.ref = "tbdLibs" }
tbdLibs-signedJwtIssuerTest = { module = "com.github.navikt.tbd-libs:signed-jwt-issuer-test", version.ref = "tbdLibs" }
tbdLibs-speedClient = { module = "com.github.navikt.tbd-libs:speed-client", version.ref = "tbdLibs" }

[plugins]
sykepenger-deployable = { id = "no.nav.sykepenger.deployable", version.ref = "sykepengerGradlePlugins" }
