apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vedtaksfeed
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
  readiness:
    path: isready
    initialDelay: 20
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  azure:
      application:
          enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: infotrygd-feed-proxy
          namespace: teamfamilie
          cluster: dev-fss
  secureLogs:
    enabled: true
  ingresses:
    - "https://vedtaksfeed.dev.intern.nav.no"
    - "https://vedtaksfeed.intern.dev.nav.no"
  env:
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-vedtaksfeed-v1
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
