apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vedtaksfeed
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 20
  readiness:
    path: /is_ready
    initialDelay: 20
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /serviceuser/data/dev/srvvedtaksfeed
  ingresses:
    - "https://vedtaksfeed.nais.preprod.local"
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: JWKS_URL
      value: http://security-token-service.default.svc.nais.local/rest/v1/sts/jwks
    - name: JWT_ISSUER
      value: https://security-token-service.nais.preprod.local
