apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vedtaksfeed
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
  readiness:
    path: isready
    initialDelay: 10
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  azure:
      application:
          enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: infotrygd-feed-proxy
          namespace: teamfamilie
          cluster: prod-fss
  secureLogs:
    enabled: true
  ingresses:
    - "https://vedtaksfeed.intern.nav.no"
  env:
    - name: KUN_KTOR_API
      value: "true"
