apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vedtaksfeed
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
  readiness:
    path: isready
    initialDelay: 10
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: infotrygd-feed-proxy
          namespace: teamfamilie
          cluster: prod-fss
        - application: infotrygd-feed-proxy-v2
          namespace: infotrygd
          cluster: prod-fss
    outbound:
      rules:
        - application: speed-api
  secureLogs:
    enabled: true
  ingresses:
    - "https://vedtaksfeed.intern.nav.no"
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-vedtaksfeed-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: none
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
