name: Bygg og deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21.x'
        cache: 'gradle'
    - name: test and build
      run: ./gradlew test build
      env:
        ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker image
      uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: tbd
        project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
        identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  aiven:
    name: aiven topic
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster:
          - dev-gcp
          - prod-gcp
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: deploy/aiven-${{ matrix.cluster }}.yml

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster:
          - dev-gcp
          - prod-gcp
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: deploy/${{ matrix.cluster }}.yml
          IMAGE: ${{ needs.build.outputs.image }}
